export const APPSTATE = Object.freeze({
    GAME_START: "APPSTATE.GAME.START",
    PLAYER_SELECTION: "APPSTATE.PLAYER.SELECTION",
    NEXT_PLAYER: "APPSTATE.NEXT.PLAYER",
    END_GAME: "APPSTATE.END.GAME"
});